<?php
/**
 * Created by PhpStorm.
 * User: Admin
 * Date: 07.04.2017
 * Time: 20:37
 */

namespace app\models;


use yii;

class Site extends yii\db\ActiveRecord
{
    public static function tableName()
    {
        return 'product'; // TODO: Change the autogenerated stub
    }

    public function getReadyForSellProducts()
    {
        $query = "SELECT p.* FROM product p 
                      LEFT JOIN problems on problems.product_id=p.id 
                      LEFT JOIN equipment e on e.product_id=p.id
                      where problems.id is null 
                      AND (e.id is null OR e.availability>1) 
                      AND p.category=1 
                      GROUP BY p.id";
        $result = Product::find()->select('product.*')
            ->leftJoin('problems', 'problems.product_id=product.id')
            ->leftJoin('equipment', 'equipment.product_id=product.id')
            ->where(["problems.id" => null])
            ->andWhere(['product.category' => 1])
            ->andWhere('equipment.id is null OR equipment.availability>0')
            ->andWhere('product.count>0')
            ->groupBy('product.id');
        $dataProvider = new yii\data\ActiveDataProvider([
            'query' => $result,
            'pagination' => [
                'pageSize' => 10,
            ]
        ]);
        return $dataProvider;
    }

    public function getAllCategories()
    {
        $query = Categories::find()->all();
        return $query;
    }

    public function getAllLaptops()
    {
        $laptops = Product::find()->select('p.id, m.name as manufacturer, p.name, p.price_internet')
            ->from('product p')
            ->joinWith(['manufacturers m'])
            ->where(['p.category' => 1])
            ->andWhere('p.count>0')
            ->andWhere('p.available>0')
            ->orderBy('m.name')
            ->asArray()
            ->all();
        return $laptops;
    }

    public function getHddAndSsd(){
        $disks = Product::find()
            ->select('c.name as category, m.name as manufacturer, product.name, product.price_internet, product.id')
            ->joinWith(['manufacturers m'])
            ->joinWith(['categories c'])
            ->where('c.id in (7,4,15)')
            ->andWhere('product.available>0')
            ->asArray()
            ->all();
        return $disks;
    }

    public function getEtc(){
        $cables = Product::find()
            ->select('c.name as category, m.name as manufacturer, product.name, product.price_internet, product.id')
            ->joinWith(['manufacturers m'])
            ->joinWith(['categories c'])
            ->where('c.id in (5,6,8,9,10,11,12,13,14)')
            ->andWhere('product.available>0')
            ->asArray()
            ->all();

        return $cables;
    }
}